### ISSUE TITLE
[10.10.0] Messes with "Play sound effects through:" Preference

### ISSUE THREAD

**Issue by NickChristensen** [deweller/switchaudio-osx#1]
My `Play sound effects through:` (on the Sound Effects tab of System Preferences -> Sound) has always been set to "Selected sound output device". I noticed, however, when I used `SwitchAudioSource -s "source"`, that setting is also changed (in addition to the expected sound output device change).

This wouldn't be a huge problem, except: it's *never* changed to the output I selected. If I change to "Display Audio", it sets it to "C-Media USB Audio Device". If I change it back to "Selected sound output device", then change to "C-Media USB Audio Device", it sets it to "Display Audio".

**Comment by heihachi88** [comment]
It's 2019 and macos version is now 10.14.3 same issue remained. If i change the sound output using interface, the sound effects output works as intended, but doing so via cli messes this up indeed.
