### ISSUE TITLE
coreaudiod[189]: SecTaskLoadEntitlements failed error=22

### ISSUE THREAD

**Issue by bfred-it** [deweller/switchaudio-osx#10]
On OS X 10.11.4, running `SwitchAudioSource -c` causes this error in system.log:

``` log
coreaudiod[189]: SecTaskLoadEntitlements failed error=22
```

But it otherwise works correctly. Thanks for this tool!

**Comment by deweller** [comment]
Not sure what causes this.  But since it is not affecting functionality, I will close it.
