### ISSUE TITLE
Doesn't list headphones when connected

### ISSUE THREAD

**Issue by InsomniacSoftware** [deweller/switchaudio-osx#11]
When the audio is set to "Internal Speakers : Built-in" in the Sound PrefPane, `SAS -c` returns "Built-in Output". When I plug in my headphones, the Sound PrefPane changes to "Headphones : Headphone Port" but SAS still returns "Built-in Output".

Is it possible to detect if the "Built-in Output" is actually the internal speakers or connected headphones?

I'm using a Late 2015 iMac running macOS Sierra 10.12.3

**Comment by zuckschwerdt** [comment]
All possible outputs are listed with `AudioSwitcher -a`. We'd need to use a different API to get something like a routing info for the devices.

**Comment by wangchou** [comment]
Maybe this api?
https://stackoverflow.com/questions/14483083/how-to-get-notifications-when-the-headphones-are-plugged-in-out-mac
