### ISSUE TITLE
Possible to set the output format?

### ISSUE THREAD

**Issue by jontelang** [deweller/switchaudio-osx#17]
Hi. Is there some way to change the format through this tool?

I mean this thing you can change in MIDI app:

<img width="641" alt="screen shot 2019-01-18 at 10 10 28 pm" src="https://user-images.githubusercontent.com/899947/51394804-e0e4ff80-1b6d-11e9-9bce-ec21dd8c3a9c.png">

I've looked through the source code and I didn't see anything, so I guess not. However a follow up question is if you know wether it is possible or not and if you could point me in a direction where I could possibly submit a PR.

Thanks

**Comment by deweller** [comment]
I don't know if this is possible.

Let me know if you are interested is submitting a PR.
