### ISSUE TITLE
Support for multiple identical named devices

### ISSUE THREAD

**Issue by Canorus** [deweller/switchaudio-osx#19]
I have two cheap usb soundcards, named USB PnP Sound Device. And I need to switch from this to that quite often. But when I tried most command line tools they would just select first one. I can workaround this with `-n` option, but it would be cleaner way of handling this if AudioSwitcher can retrieve and select through device hardware ID. Thanks.

**Comment by nbolender** [comment]
See #25

**Comment by deweller** [comment]
Closed in favor of #25
