### ISSUE TITLE
Doesn't appear to work with duplicate audio devices

### ISSUE THREAD

**Issue by tdhopper** [deweller/switchaudio-osx#2]
I have two HDMI monitors. Only one is connected to an audio device. I see this

```
$ ./SwitchAudioSource -a
Built-in Microphone (input)
Built-in Output (output)
HDMI (output)
HDMI (output)
```

If I run `-s HDMI`, it may or may not switch to the right device. 

Is there some way to distinguish the devices?

**Comment by SportySeb** [comment]
I run into the same issue. I have two equal USB-sound-adapter from Logitech and need to switch between each other. Unfortunatly they are shown with exactly the same name in the list of available devices.

Is there any solution to get it work also in my case ?

Thank you in advance

**Comment by Hokie333** [comment]
do
 `$ ./SwitchAudioSource -s (name of device)`

which will select the first device with that name, then

`$ ./SwitchAudioSource -n`

that'll select the next device in the -a list, which will probably be the one you want. I have 2 "Line Out"s (the second one being the one I need), and this works for me. Hopefully your devices are always consistent like mine are.
