### ISSUE TITLE
Built in output doesn't works...

### ISSUE THREAD

**Issue by seevoid** [deweller/switchaudio-osx#24]
Hi, 
I have a piece of a jack stucked in my audio entry, so I need to force my mac to switch to the integrate speakers. 
I used SwitchAudio to do that, I have the message that tells me it's good : "output audio device set to "Built-in Output"". Unfortunately there is no sound and the volume bar is grey :/

Did you experienced this issue ? 

Thanks

**Comment by zuckschwerdt** [comment]
That's a hardware limitation. "Built-in Output" will be routed to speakers, headphone or SPDIF as needed. As long as the port is occupied the internal output won't work.
