### ISSUE TITLE
Doesn't install on Catalina

### ISSUE THREAD

**Issue by AlexPasternak** [deweller/switchaudio-osx#27]
There was an earlier issue about not supporting newer macOS but it was Closed. However I cannot install on 10.15.6. I'll attach the full failure, but the main issue seems to be that the platform is unsupported. Could this be fixed please, as I really like this utility?

<pre>
warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.5, but 
the range of supported deployment target versions is 10.6 to 10.15.99. (in target 'SwitchAudioSource' from project 'AudioSwitcher')
</pre>

[2020-09-10 brew failure.txt](https://github.com/deweller/switchaudio-osx/files/5204445/2020-09-10.brew.failure.txt)

**Comment by wangchou** [comment]
I just installed it on 10.15.6. It works.

After ```brew install switchaudio-osx```

It downloads ```https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.catalina.bottle.2.tar.gz```

but in your brew failure.txt

It downloaded ```https://github.com/deweller/switchaudio-osx/archive/1.0.0.tar.gz```

Not sure why, but I guess it is fixed.
