### ISSUE TITLE
Toggle Switch

### ISSUE THREAD

**Issue by becauseim** [deweller/switchaudio-osx#30]
I have two quick actions to turn on separate devices, but I would like to have one action to switch between the two devices. how do I do this?

<img width="591" alt="Снимок экрана 2021-03-20 в 20 06 11" src="https://user-images.githubusercontent.com/23287366/111878096-bdb97300-89b7-11eb-94f4-bd141f80e25c.png">

**Comment by zuckschwerdt** [comment]
I use something like `[ "$(AudioSwitcher -c)" = "Built-in Output" ] && AudioSwitcher -s "DisplayPort" || AudioSwitcher -s "Built-in Output"`

**Comment by becauseim** [comment]
> I use something like `[ "$(AudioSwitcher -c)" = "Built-in Output" ] && AudioSwitcher -s "DisplayPort" || AudioSwitcher -s "Built-in Output"`

Thank нщг! But i don't understand how to use it. My example is based on[ this one](https://www.fredzhao.com/switch-audio-input-output-devices-with-keyboard-shortcuts-on-os-x)

**Comment by zuckschwerdt** [comment]
It's just the Shell Script, like the one you already have. E.g. replace
```
/usr/local/bin/SwitchAudioSource -t output -s 'Cayin N3Pro'
```
with
```
[ "$(/usr/local/bin/SwitchAudioSource -c)" = "Built-in Output" ] && /usr/local/bin/SwitchAudioSource -s "Cayin N3Pro" || /usr/local/bin/SwitchAudioSource -s "Built-in Output"
```

or, simpler, maybe just use

```
/usr/local/bin/SwitchAudioSource -n
```

which will switch to each next audio output available (A -> B -> ... -> A).

**Comment by becauseim** [comment]
Thank you! Unfortunately, an error comes out when calling a quick action.
<img width="591" alt="Снимок экрана 2021-03-20 в 23 39 35" src="https://user-images.githubusercontent.com/23287366/111884949-d20c6880-89d5-11eb-8d5c-610ce6ee9012.png">

`/usr/local/bin/SwitchAudioSource -n
`
this option is not suitable because you need to switch between two devices out of three (without built-in macbook speakers)

**Comment by becauseim** [comment]
my goal is to switch between two external output devices with one keyboard shortcut

**Comment by zuckschwerdt** [comment]
Try in Terminal.app to see what's wrong.

**Comment by deweller** [comment]
Closing this because it is not an issue directly related to switchaudio-osx.

I hope you are able to resolve your problem with your bash script.

**Comment by gianpaj** [comment]
If anybody lands here, I wrote this bash script to toggle between 2 audio interfaces with Alfred.

https://gist.github.com/gianpaj/6334e6a4cd1f9fe48b58c1e7b8ccd5a2

Though this Alfred Workflow is readily done and works great :) 
https://github.com/dkarter/alfred-switch-audio
