### ISSUE TITLE
Also as a binary file?

### ISSUE THREAD

**Issue by UnixCro** [deweller/switchaudio-osx#31]
Could you please provide the pre-made binary file for download here. I want to use this program without having to install Homebrew.

Thank you

**Comment by deweller** [comment]
You can download the pre-made binaries here:

arm64 big sur
https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.arm64_big_sur.bottle.2.tar.gz
SHA256: d9971abdf1ae93055e74f4e1b48ad4ed0cf835069ed0750594156279d18b702e

big sur
https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.big_sur.bottle.2.tar.gz
SHA256: d577b2297c1865399ecbe4c7f2ac491063d75c786387502246b30d32e2606ee7

catalina
https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.catalina.bottle.2.tar.gz
SHA256: 4a1ad0824d878dcabb3d7ffe4ad911f850383dbf2db28100e58f28cbc96657b7

el capitan
https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.el_capitan.bottle.2.tar.gz
SHA256: 515b762164648d739ae36f8c5013d250d84af1264bf3ee366ed35adae2f44208

high sierra
https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.high_sierra.bottle.2.tar.gz
SHA256: 26af506ea42b83ae8ccde71ed8b7666ccf3e3a349b2dd8958af7025854ffefd3

mojave
https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.mojave.bottle.2.tar.gz
SHA256: 85d0fe91c72d1a61e331e475af4e6ded9d0ca3581612c1934835bc44653fe407

sierra
https://homebrew.bintray.com/bottles/switchaudio-osx-1.0.0.sierra.bottle.2.tar.gz
SHA256: 89ed040cc50c7b7ad88a903da5351cfa0027a4daf22cf73f2713e0887847c5d1



You can find this list by visiting https://formulae.brew.sh/formula/switchaudio-osx#default and clicking on the JSON link.

**Comment by DanAykroyd256** [comment]
Hi @deweller,

I've noticed that the latest version is 1.1.0, but the one posted here for the premade binaries is still 1.0.0. I've tried looking at the JSON in Homebrew website, but it seems to link to the same source files that are here (not the binaries). I've tried replacing the "1.0.0" in the URL for "1.1.0" but the file can't be found there neither.

Are the premade binaries posted somewhere? Can those be downloading from the JSON Homebrew file or Homebrew compiles on the fly when one installs an app; hence the binaries are not already uploaded?

Thanks for your support and maintaining these project!

**Comment by deweller** [comment]
The homebrew project switched away from bintray this year.  And the new format appears to be using Github packages which require authentication.

I can't see any way to download the premade binaries any longer without using homebrew or docker.
