### ISSUE TITLE
Sound Effects not changing

### ISSUE THREAD

**Issue by Willibaur** [deweller/switchaudio-osx#39]
Hi, thanks for this awesome script.

I've come accross an issue with the `Sounds Effects` source not being updated once I change my `output source` is this a known issue?
I'm not sure if there is anything I need to tweak locally.

I'm using an Edifier set of speakers connected via Bluetooth, I can switch sound without problem but not the effects itself.

**Comment by ToBro14** [comment]
I have the same issue.
This bug was reported previously, but it was never fixed:
https://github.com/deweller/switchaudio-osx/issues/12

**Comment by deweller** [comment]
I was not able to fix this.  I took a look at the code and I can't find anything wrong.

This might be fixed in Mac OS X 12.

**Comment by n8io** [comment]
I ended up running the following work around:

```sh
switchaudiosource -t output -i <deviceId> && switchaudiosource -t system <deviceId>
```

**Comment by revans23** [comment]
> I ended up running the following work around:
> 
> ```shell
> switchaudiosource -t output -i <deviceId> && switchaudiosource -t system <deviceId>
> ```

+1

This solution is the easiest!
