### ISSUE TITLE
Cannot install with brew without Xcode?

### ISSUE THREAD

**Issue by dzg** [deweller/switchaudio-osx#4]
I'm trying to install this using homebrew with
`brew install switchaudio-osx`
but it reports:
```
switchaudio-osx: A full installation of Xcode.app is required to compile this software.
Installing just the Command Line Tools is not sufficient.
Xcode can be installed from the App Store.
Error: An unsatisfied requirement failed this build.
```

Any way around this?

**Comment by zuckschwerdt** [comment]
The project relies on the building facilities provided by Xcode. This could be replaced by a generic GNU Make -- or preferably something modern like CMake, Ninja. TL;DR currently not but it can be added.
