### ISSUE TITLE
Get and set audio properties (Volume, Mute)?

### ISSUE THREAD

**Issue by czokie** [deweller/switchaudio-osx#40]
I have my own bash scripts with calls to AppleScript commands that wrap around your data, to set input and output volume levels to a template, before doing various activities on my mac. It would be awesome if your app natively supported this.

[https://developer.apple.com/library/archive/qa/qa1016/_index.html](https://developer.apple.com/library/archive/qa/qa1016/_index.html)

I did some searching and found the article above. However, while searching, I noted that the audio device libraries you are using are deprecated anyway. Compiling on a recent MacOS build generates warnings regarding this.

Do you have plans to convert to newer audio libraries, and if so, would you consider integrating options to get and set audio properties for specified devices?

**Comment by deweller** [comment]
See #49 for the mute setting
