### ISSUE TITLE
Leave input through the built-in microphone when headphones are connected.

### ISSUE THREAD

**Issue by kuzlich** [deweller/switchaudio-osx#43]
I use airpods for calls, but I have a separate good microphone. I have to constantly switch to it after connecting the headphones via Bluetooth. Is there a script that I can use switchaudio to turn on my microphone? Getting into sound settings several times a day is getting tiring.

**Comment by deweller** [comment]
You can create an apple script or an automator action to run this command line utility.

I'm not sure how to automatically connect it when you plug in your headphones.  Maybe someone else can help you with that.
