### ISSUE TITLE
"Selected sound output device" changed if changes output

### ISSUE THREAD

**Issue by MakotoYamanaka** [deweller/switchaudio-osx#44]
I set [System Preferences]>[Sound]>[Sound Effects]>[Play sound effects through] to "Selected sound output device".
If SwitchAudioSource changes output, this setting was changed to some device.

I took a video, so I would like you to watch it.
(Sorry if it difficult to understand because Japanese environment.)
https://www.dropbox.com/s/27eravi8f2nnld4/SwitchAudioSource_20221005.mov

This problem does not occur in System Preferences and Control Center.
I would appreciate it if you could fix this problem.
Alternatively, I can avoid this problem if you create an option that can be set to "Selected sound output device".

Thanks.

SwitchAudioSource 1.1.0/macOS Monterey 12.6/MacBook Pro(16-inch,2019)

**Comment by deweller** [comment]
Same issue as #39.
