### ISSUE TITLE
Cannot get this to work

### ISSUE THREAD

**Issue by rickdhoy** [deweller/switchaudio-osx#46]
Hi All,

i have installed and I have checked and can get some of the commands to work, however when i try tho add the name of the device I want too control it doe not work.

rickhoy@MacBook-Pro ~ % SwitchAudioSource -s USB PnP Sound Device
Could not find an audio device named "USB" of type output.  Nothing was changed.

The below is the list of devices. I'm trying to use USB Pnp Sound Device. I can also use the command "SwitchAudioSource -n" and it will cycle through the devices.

@MacBook-Pro ~ % SwitchAudioSource -a       
Rick iPhone Microphone
Display Audio
Display Audio
USB PnP Sound Device
Generic USB Audio Device   
MacBook Pro Microphone
MorphVOX Audio
AirParrot
LED Cinema Display
LED Cinema Display
Display Audio
Display Audio
USB PnP Sound Device
Generic USB Audio Device   
MacBook Pro Speakers
MorphVOX Audio
AirParrot

Any suggestions would be great.

**Comment by zuckschwerdt** [comment]
You need to quote: `rickhoy@MacBook-Pro ~ % SwitchAudioSource -s "USB PnP Sound Device"` -- one string not four words.

**Comment by rickdhoy** [comment]
Hi,

Thanks for the response. Brilliant, worked.

Apologies as I am very new to all this and still learning :-)

Have a Merry Christmas and Happy New Year
