### ISSUE TITLE
Long execution time (upwards of 2 minutes)

### ISSUE THREAD

**Issue by nerolite** [deweller/switchaudio-osx#62]
_switchaudio-osx_ is taking very long (1:58 seconds recorded) to execute commands that previously were done in mere seconds.

These commands are:
`/opt/homebrew/bin/SwitchAudioSource -s AirPods_Pro -t output`
`/opt/homebrew/bin/SwitchAudioSource -s AirPods_Pro -t input`

System:
MacOS Ventura v.13.6 (22G120)
switchaudio-osx v.1.2.2

**Comment by deweller** [comment]
Interesting.  Do you experience the same delay when you switch using the standard System Preferences dialog?

**Comment by nerolite** [comment]
The delay was not there in the standard System Preferences dialog.

However, after several _consecutive_ restarts the issue seems to be resolved. _switchaudio-osx_ is now responding quickly.

I reckon we can close this topic. It seems to have been an isolated issue. Thanks!
