### ISSUE TITLE
Work with newer OS'es?

### ISSUE THREAD

**Issue by patgmac** [deweller/switchaudio-osx#7]
Is there any reason this wouldn't work with 10.9+?

I just did a quick test on a 10.9 system because I had a need for it, but just curious if there's any reason I shouldn't use this tool beyond the stated 10.8 listed in the README?

**Comment by deweller** [comment]
I just haven't updated the README.  If it works for you in 10.9 and/or 10.10, please let me know and I will update it.

**Comment by deweller** [comment]
I just tested this on my OS 10.10 system and it works just fine.

**Comment by paulsri** [comment]
Has anyone tested on 10.13 yet? See this thread:

https://www.alfredforum.com/topic/9896-airpods-audio-source-selector/

**Comment by deweller** [comment]
If anyone tries it on 10.13, please let me know if it works.
